wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/bg.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:Dell Inc. DELL U2518D 3C4YP92CBUDL
    path = ~/.config/hypr/bg.png
    fit_mode = cover
}
